force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>date and time of the log</description>
    <inlineHelpText>the date and the time for the log</inlineHelpText>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Details for the log</description>
    <inlineHelpText>Details of the log</inlineHelpText>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <inlineHelpText>The Name of Either Apex Class or Apex Trigger</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLog.cls
public class ErrorLog {
    public static void insertErrorLog(String processName, String logDetails) {
        Error_Log__c errorLogObj = new Error_Log__c();
        errorLogObj.Log_Details__c = logDetails;
        errorLogObj.Process_Name__c = processName;
        errorLogObj.Log_Date_Time__c = DateTime.now();
        // System.debug(logDetails + ' ' + processName + ' ' + DateTime.now());
        insert errorLogObj;
    }
}