force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the Attendee</description>
    <inlineHelpText>enter the email of the attendee</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>location of the event</description>
    <inlineHelpText>enter the event location</inlineHelpText>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>name for the event</description>
    <inlineHelpText>enter the name for the event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>organizer for the event</description>
    <inlineHelpText>the organizer of the event</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>start date and time for the event</description>
    <inlineHelpText>enter the start date for the event</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>event attendees list who will attend the event.</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>attendee who will attend the event</description>
    <inlineHelpText>attendee who will attend the event</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Event</description>
    <inlineHelpText>The Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Event organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email id of the event organizer</description>
    <inlineHelpText>enter the email id of the event organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location of the event</description>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeConfirmationHelper.cls
public class AttendeeConfirmationHelper {
    public static void emailHandler(List<Event_Attendee__c> currentEventAttendees) {

        // Master Mail List -> storing all the mails in a list
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        
        // creating a set of attendee and event from event attendee using trigger.new
        Set<Id> currentAttendeeSet = new Set<Id>();
        Set<Id> currentEventSet = new Set<Id>();

        // adding attendee and event id to the set -> since we are using a set, we will have unique id only 
        for (Event_Attendee__c currentEA : currentEventAttendees) {
            currentAttendeeSet.add(currentEA.Attendee__c);
            currentEventSet.add(currentEA.Event__c);
        }

        // map of id and event obj -> fetching id, name, start and location.name and organizer.name from event object (if the id of event is present in the event set)
        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([SELECT Id, Name__c, Start__c, Location__r.Name, Organizer__r.Name FROM Event__c WHERE Id IN: currentEventSet]);

        // map of id and attendee obj -> fetching id, name, email from attendee object (if the id of attendee is present in attendee set)
        Map<Id, Attendee__c> attendeeMap = new Map<Id, Attendee__c>([SELECT Id, Name, Email__c FROM Attendee__c WHERE Id IN: currentAttendeeSet]);

        // iterating on event attendee retrieved from trigger.new
        for (Event_Attendee__c currentEA : currentEventAttendees) {

            // storing the attendee object by matching the id in attendee map
            Attendee__c attendee = attendeeMap.get(currentEA.Attendee__c);
            // storing the event object by matching the id in event map
            Event__c event = eventMap.get(currentEA.Event__c);

            //Email subject
            String subject = 'Pass for the ' + event.Name__c;
            // Email Body
            String plainTextBody = 'Dear ' + attendee.Name + ', ';
            plainTextBody += 'Thank you for registering for '+ event.Name__c +' which will be Organized on ' + event.Start__c +' & will be held in ' + event.Location__r.Name + '. ';
            plainTextBody += 'We are excited to have you, see you at the event. ';
            plainTextBody += 'Thanks, '+ event.Organizer__r.Name;
        
            // adding a single mail to master list -> using EmailHelper class that I created to setup a single mail
            mails.add(EmailHelper.singleEmailSetup(new String[]{attendee.Email__c}, subject, plainTextBody));
            // Sending the mails to emails in master email list using EmailHelper class
            EmailHelper.sendEmail(mails);
        }
    }
}