force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker in the event</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>phone number of the speaker</description>
    <inlineHelpText>enter the phone number of the speaker</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CreateSpeakerServiceTest.cls
@isTest
private class CreateSpeakerServiceTest {
    
    // @isTest
    // static void test1(){

    //     Test.startTest();

    //         RestContext.request = new RestRequest();
    //         RestContext.response = new RestResponse();

    //         String respo = CreateSpeakerService.createSpeaker('Ferocious chipmunk', 'chipmunk@gmail.com', '9992987895');
    //         Speaker__c speaker = [SELECT Id, Name, Phone__c FROM Speaker__c WHERE Name = 'Ferocious chipmunk'];

    //         System.assertEquals('Ferocious chipmunk', speaker.Name);
    //         System.assertEquals(200, RestContext.response.statusCode);
            

    //     Test.stopTest();
    // }

    @isTest
    static void test2(){

        Test.startTest();

            // RestContext.request = new RestRequest();
            RestContext.response = new RestResponse();

            String respo = CreateSpeakerService.createSpeaker('Ferocious chipmunk', 'chipmunk@gmail.com', '9992987895');
            String respo2 = CreateSpeakerService.createSpeaker('Ferocious chipmunk', 'chipmunk@gmail.com', '9992987895');
            List<Speaker__c> speaker = [SELECT Id, Name, Phone__c FROM Speaker__c WHERE Name = 'Ferocious chipmunk'];

            System.assertEquals(1, speaker.size());
            System.assertEquals(400, RestContext.response.statusCode);
            

        Test.stopTest();
    }
}