force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker in the event</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the speaker</description>
    <inlineHelpText>enter the email of the speaker</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>phone number of the speaker</description>
    <inlineHelpText>enter the phone number of the speaker</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CreateSpeakerService.cls
@RestResource(urlMapping='/CreateSpeaker/*')

global class CreateSpeakerService {


    @HttpPost
    global static String createSpeaker(String name, String email, String phone) {
        Speaker__c speaker = new Speaker__c(
           Name = name,
           Email__c = email,
           Phone__c = phone
        );

        Try {
            RestResponse res = RestContext.response;
            insert speaker;
            res.statusCode = 200;
            return 'Successful';
        } catch (Exception e) {
            RestResponse res = RestContext.response;
            res.statusCode = 400;
            return 'Insertion Failed';
        }
    }   
    
}