force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>end date and time for the event</description>
    <inlineHelpText>enter the end date and time for the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is the show live or not</description>
    <inlineHelpText>is the show live or not live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>name for the event</description>
    <inlineHelpText>enter the name for the event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>start date and time for the event</description>
    <inlineHelpText>enter the start date for the event</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker who will speak at the event</description>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>event</description>
    <inlineHelpText>event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>speaker for the event</description>
    <inlineHelpText>enter speaker of the event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker in the event</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateSpeakerTest.cls
@isTest
public class DuplicateSpeakerTest {

    @TestSetup
    static void makeData() {

        List<Event__c> eventsToInsert = new List<Event__c>(); 

        Event__c testEvent = new Event__c(
            Name__c = 'test1',
            Live__c = true,
            Start__c = Datetime.newInstance(2023, 4, 1, 12, 00, 00),
            End__c = Datetime.newInstance(2023, 4, 2, 12, 00, 00)
        );
        eventsToInsert.add(testEvent);

        Event__c testEvent1 = new Event__c(
            Name__c = 'test2',
            Live__c = true,
            Start__c = Datetime.newInstance(2023, 4, 2, 14, 00, 00),
            End__c = Datetime.newInstance(2023, 4, 3, 18, 00, 00)
        );
        eventsToInsert.add(testEvent1);

        Event__c testEvent2 = new Event__c(
            Name__c = 'test3',
            Live__c = true,
            Start__c = Datetime.newInstance(2023, 3, 28, 12, 00, 00),
            End__c = Datetime.newInstance(2023, 4, 1, 14, 00, 00)
        );     
        eventsToInsert.add(testEvent2);

        insert eventsToInsert;

        List<Speaker__c> speakersToInsert = new List<Speaker__c>();

        Speaker__c testSpeaker = new Speaker__c(
            Name = 'test speaker'
        );
        speakersToInsert.add(testSpeaker);

        // Speaker__c testSpeaker2 = new Speaker__c(
        //     Name = 'test speaker 2'
        // );
        // speakersToInsert.add(testSpeaker2);

        insert speakersToInsert;

        Event_Speaker__c testEventSpeaker = new Event_Speaker__c(
            Event__c = testEvent.Id,
            Speaker__c = testSpeaker.Id
        );
        insert testEventSpeaker;
    }

    @isTest
    static void myTest() {
        
        // Test.startTest();

        Event_Speaker__c testEventSpeaker = new Event_Speaker__c(
            Event__c = [SELECT Id FROM Event__c WHERE Name__c = 'test2' LIMIT 1].Id,
            Speaker__c = [SELECT Id FROM Speaker__c WHERE Name = 'test speaker' LIMIT 1].Id
        );

        Event_Speaker__c testEventSpeaker2 = new Event_Speaker__c(
            Event__c = [SELECT Id FROM Event__c WHERE Name__c = 'test3'].Id,
            Speaker__c = [SELECT Id FROM Speaker__c WHERE Name = 'test speaker'].Id
        );

        
        try {
            insert testEventSpeaker;
        } catch (Exception e) {
            system.debug(e.getMessage());
        }

        try {
            insert testEventSpeaker2;
            // Assert.fail('DmlException expected');
        } catch (Exception e) {
            system.debug(e.getMessage());
        }

        List<Event_Speaker__c> es = [SELECT Event__c, Speaker__c FROM Event_Speaker__c];

        System.assertEquals(true, es.contains(testEventSpeaker));
        System.assertEquals(false, es.contains(testEventSpeaker2));
        // System.assertEquals('Speaker is already booked for this time slot.', message2);
        
        // Test.stopTest();
    }

}