force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>end date and time for the event</description>
    <inlineHelpText>enter the end date and time for the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>name for the event</description>
    <inlineHelpText>enter the name for the event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>start date and time for the event</description>
    <inlineHelpText>enter the start date for the event</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker who will speak at the event</description>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>event</description>
    <inlineHelpText>event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>speaker for the event</description>
    <inlineHelpText>enter speaker of the event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker in the event</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateEventSpeakerHandler.cls
public class DuplicateEventSpeakerHandler {
    public static void handleDuplicateSpeaker(List<Event_Speaker__c> newEventSpeakers) {
        Set<Id> newSpeakerList = new Set<Id>();
        Set<Id> newEventList = new Set<Id>();

        for (Event_Speaker__c eventSpeaker : newEventSpeakers) {
            newSpeakerList.add(eventSpeaker.Speaker__c);
            newEventList.add(eventSpeaker.Event__c);
        }

        // Fetching All the Existing Events
        List<Event__c> OldEventsList = [SELECT Id, Name__c, Start__c, End__c FROM Event__c WHERE End__c > Today];

        //Map -> event id, event object
        Map<Id, Event__c> oldEventsMap = new  Map<Id, Event__c>();

        for (Event__c oldEvent : OldEventsList) {
            oldEventsMap.put(oldEvent.Id, oldEvent);
        }


        /* INIT Setup : */
        //key -> speaker Id, value -> list of events
        Map<Id, List<Event__c>> speakerToEventsMap = new Map<Id, List<Event__c>>();

        // soql -> to get event id, speaker id from event speaker order by event start date (ascending)
        for (Event_Speaker__c eventSpeaker : [SELECT Id, Event__c, Speaker__c, Event__r.Start__c FROM Event_Speaker__c WHERE Speaker__c IN: newSpeakerList ORDER BY Event__r.Start__c]) {
            if (speakerToEventsMap.containsKey(eventSpeaker.Speaker__c)) {
                speakerToEventsMap.get(eventSpeaker.Speaker__c).add(oldEventsMap.get(eventSpeaker.Event__c));
            } else {
                speakerToEventsMap.put(eventSpeaker.Speaker__c, new List<Event__c>{oldEventsMap.get(eventSpeaker.Event__c)});
            }
        }

        
        for (Event_Speaker__c eventSpeaker : newEventSpeakers) {
            if (speakerToEventsMap.containsKey(eventSpeaker.Speaker__c)) {
                //checking for conflict :
                Event__c eventNow = oldEventsMap.get(eventSpeaker.Event__c);
                List<Event__c> existingEvents = speakerToEventsMap.get(eventSpeaker.Speaker__c);
                integer n = existingEvents.size();

                // Case 1 : Event should go at Start
                if (eventNow.End__c < existingEvents.get(0).Start__c) {
                    existingEvents.add(0, eventNow);
                    speakerToEventsMap.get(eventSpeaker.Speaker__c).add(eventNow);
                    continue;
                }
                
                // Case 2 : Event should go at End
                if (eventNow.Start__c > existingEvents.get(n - 1).End__c) {
                    existingEvents.add(eventNow);
                    speakerToEventsMap.get(eventSpeaker.Speaker__c).add(eventNow);
                    continue;
                }

                // Case 3 : Event should go in between

                boolean mark = false;

                for (integer i = 1; i < n; i++) {
                    if (eventNow.Start__c > existingEvents.get(i - 1).End__c && eventNow.End__c < existingEvents.get(i).Start__c) {
                        existingEvents.add(i, eventNow);
                        mark = true;
                    }

                    if (mark) break;
                }
                
                // Case 4 : Invalid Event
                if (!mark) {
                    eventSpeaker.addError('Speaker is already booked for this time slot.');
                }

                speakerToEventsMap.get(eventSpeaker.Speaker__c).add(eventNow);
            }            
        }
    }
}


    // Set<Id> speakerIds = new Set<Id>();

    // for (Event_Speaker__c eventSpeaker : Trigger.new) {
    //     speakerIds.add(eventSpeaker.Speaker__c);
    // }

    // Map<Id, Event_Speaker__c> existingEvents = new Map<Id, Event_Speaker__c>();
    

    // for (Event_Speaker__c eventSpeaker : [SELECT Id, Event__c, Speaker__c, Event__r.Name__c FROM Event_Speaker__c WHERE Speaker__c IN :speakerIds]) {
    //     existingEvents.put(eventSpeaker.Speaker__c, eventSpeaker);
    // }


    // for (Event_Speaker__c eventSpeaker : Trigger.new) {
    //     if (existingEvents.containsKey(eventSpeaker.Speaker__c)) {
    //         Event_Speaker__c existingEvent = existingEvents.get(eventSpeaker.Speaker__c);
    //         eventSpeaker.addError('Speaker is already associated with event ' + existingEvent.Event__r.Name__c);

    //     } else {
    //         speakerIds.add(eventSpeaker.Speaker__c);
    //         existingEvents.put(eventSpeaker.Speaker__c, eventSpeaker);
    //     }
    // }