force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>end date and time for the event</description>
    <inlineHelpText>enter the end date and time for the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is the show live or not</description>
    <inlineHelpText>is the show live or not live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>maximum seats in the event</description>
    <inlineHelpText>enter the maximum number of seats in the event.</inlineHelpText>
    <label>Max Seats</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>name for the event</description>
    <inlineHelpText>enter the name for the event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>organizer for the event</description>
    <inlineHelpText>the organizer of the event</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>start date and time for the event</description>
    <inlineHelpText>enter the start date for the event</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Event organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email id of the event organizer</description>
    <inlineHelpText>enter the email id of the event organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventsManagerTest.cls
@isTest
private class EventsManagerTest {
    @TestSetup
    static void makeData(){


        Event_Organizer__c organizer = new Event_Organizer__c (
            Name = 'Harshit Kumar',
            Email__c = 'harshit.kumar.mirketa@gmail.com'
        );

        insert organizer;

        Event__c event = new Event__c(
            Name__c = 'test1',
            Max_Seats__c = 100,
            Organizer__c = organizer.Id,
            Live__c = true,
            Start__c = Datetime.newInstance(2023, 4, 7, 12, 00, 00),
            End__c = Datetime.newInstance(2023, 4, 9, 12, 00, 00)
        );

        insert event;
    }

    @isTest
    static void checkData() {
        // RestRequest request = new RestRequest();
        // request.requestUri = 'https://mirketa76-dev-ed.develop.my.salesforce.com/services/apexrest/Events/';
        // request.httpMethod = 'GET';
        // RestContext.request = request;
        

        Event__c events = [SELECT Id, Name__c, Max_Seats__c, Start__c, Organizer__r.Name, Organizer__r.Email__c FROM Event__c];
        List<Event__c> responseList = EventsManager.getEvents();
        Event__c response = responseList.get(0);

        System.assert(responseList != null);
        System.assertEquals(events.Id, response.Id);
        System.assertEquals(events.Name__c, response.Name__c);
        System.assertEquals(events.Max_Seats__c, response.Max_Seats__c);
        System.assertEquals(events.Start__c, response.Start__c);
        System.assertEquals(events.Organizer__r.Name, response.Organizer__r.Name);
        System.assertEquals(events.Organizer__r.Email__c, response.Organizer__r.Email__c);
        
    }
}