force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>maximum seats in the event</description>
    <inlineHelpText>enter the maximum number of seats in the event.</inlineHelpText>
    <label>Max Seats</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>name for the event</description>
    <inlineHelpText>enter the name for the event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>organizer for the event</description>
    <inlineHelpText>the organizer of the event</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>start date and time for the event</description>
    <inlineHelpText>enter the start date for the event</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Event organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email id of the event organizer</description>
    <inlineHelpText>enter the email id of the event organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventsManager.cls
@RestResource(urlMapping='/Events/*')

global class EventsManager {

    @HttpGet
    global static void getEvents() {

        // RestResponse response = new RestResponse();

        List<Event__c> eventsList = [SELECT Name__c, Start__c, Max_Seats__c, Organizer__r.Name, Organizer__r.Email__c FROM Event__c];
        List<Object> eventsListToSend = new List<Object>();

        for (Event__c event : eventsList) {
            Map<String, Object> finalMap = new Map<String, Object>();
            Map<String, Object> eventMap = new Map<String, Object>();
            Map<String, Object> organizerMap = new Map<String, Object>();

            eventMap.put('name', event.Name__c);
            eventMap.put('date_time', event.Start__c);
            eventMap.put('max_attendee', event.Max_Seats__c);

            organizerMap.put('name', event.Organizer__r.Name);
            organizerMap.put('email', event.Organizer__r.Email__c);

            
            finalMap.put('event_organizer', organizerMap);
            finalMap.put('event', eventMap);

            eventsListToSend.add(finalMap);
        }

        // response.setBody()
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(eventsListToSend));
        
        // return eventsList;
    }
    
}