force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker who will speak at the event</description>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>event</description>
    <inlineHelpText>event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>speaker for the event</description>
    <inlineHelpText>enter speaker of the event</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>speaker in the event</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SpeakerRegistrationController.cls
public class SpeakerRegistrationController {

    public Speaker__c speaker {get; set;}

    public Event_Speaker__c eventSpeaker {get; set;}

    public SpeakerRegistrationController() {
        speaker = new Speaker__c();
        eventSpeaker = new Event_Speaker__c();

        Id currentRecordId = ApexPages.currentPage().getParameters().get('id');
        if (currentRecordId != null) {
            eventSpeaker.Event__c = currentRecordId;
        }
    }

    public void save() {
        Savepoint sp = Database.setSavepoint();
        Try {
            insert speaker;
            eventSpeaker.Speaker__c = speaker.Id;
            insert eventSpeaker;
        } catch (Exception e) {
            Database.rollback(sp);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
            ErrorLog.insertErrorLog('Speaker Registration Controller', e.getMessage());
        } finally {
            speaker = new Speaker__c();
            eventSpeaker = new Event_Speaker__c();
        }
    }
}