force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>end date and time for the event</description>
    <inlineHelpText>enter the end date and time for the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is the show live or not</description>
    <inlineHelpText>is the show live or not live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteOldEvents.cls
public class DeleteOldEvents implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('Select Id from Event__c Where End__c <= LAST_N_MONTHS:2 AND Live__c = true');
    }

    public void execute(Database.BatchableContext bc, List<Event__c> eventScope) {
       delete eventScope;
    }

    public void finish( Database.BatchableContext bc ) {
        String[] toAddresses = new String[] {'pushkar.raja@mirketa.com'};
        String subject = 'Execution of the batch has been processed';
        String plainTextBody = 'Batch for deleting 2 months old has been processed';

        

        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        mails.add(EmailHelper.singleEmailSetup(toAddresses, subject, plainTextBody));
        EmailHelper.sendEmail(mails);
    }
}